export const topGenres = [
  { genre: "Action", id: 1 },
  { genre: "Adventure", id: 2 },
  { genre: "Comedy", id: 4 },
  { genre: "Drama", id: 8 },
  { genre: "Fantasy", id: 10 },
  { genre: "Horror", id: 14 },
  { genre: "Mystery", id: 7 },
  { genre: "Psychological", id: 40 },
  { genre: "Romance", id: 22 },
  { genre: "Sci-Fi", id: 24 },
  { genre: "Slice of Life", id: 36 },
  { genre: "Supernatural", id: 37 },
];

export const genresId = [
  { genre: "Racing", id: 3 },
  { genre: "Avant Garde", id: 5 },
  { genre: "Mythology", id: 6 },
  { genre: "Ecchi", id: 9 },
  { genre: "Strategy Game", id: 11 },
  { genre: "Historical", id: 13 },
  { genre: "Kids", id: 15 },
  { genre: "Martial Arts", id: 17 },
  { genre: "Mecha", id: 18 },
  { genre: "Music", id: 19 },
  { genre: "Parody", id: 20 },
  { genre: "Samurai", id: 21 },
  { genre: "School", id: 23 },
  { genre: "Shoujo", id: 25 },
  { genre: "Shounen", id: 27 },
  { genre: "Space", id: 29 },
  { genre: "Sports", id: 30 },
  { genre: "Super Power", id: 31 },
  { genre: "Vampire", id: 32 },
  { genre: "Military", id: 38 },
  { genre: "Detective", id: 39 },
  { genre: "Thriller", id: 41 },
  { genre: "Seinen", id: 42 },
  { genre: "Josei", id: 43 },
  { genre: "Award-Winning", id: 46 },
  { genre: "Gourmet", id: 47 },
  { genre: "Workplace", id: 48 },
  { genre: "Adult Cast", id: 50 },
  { genre: "Anthropomorphic", id: 51 },
  { genre: "CGDCT", id: 52 },
  { genre: "Childcare", id: 53 },
  { genre: "Combat Sports", id: 54 },
  { genre: "Delinquents", id: 55 },
  { genre: "Educational", id: 56 },
  { genre: "Gag Humor", id: 57 },
  { genre: "Gore", id: 58 },
  { genre: "High Stakes Game", id: 59 },
  { genre: "Idols (Female)", id: 60 },
  { genre: "Idols (Male)", id: 61 },
  { genre: "Isekai", id: 62 },
  { genre: "Iyashikei", id: 63 },
  { genre: "Love Polygon", id: 64 },
  { genre: "Mahou Shoujo", id: 66 },
  { genre: "Medical", id: 67 },
  { genre: "Organized Crime", id: 68 },
  { genre: "Otaku Culture", id: 69 },
  { genre: "Performing Arts", id: 70 },
  { genre: "Pets", id: 71 },
  { genre: "Reincarnation", id: 72 },
  { genre: "Reverse Harem", id: 73 },
  { genre: "Romantic Subtext", id: 74 },
  { genre: "Showbiz", id: 75 },
  { genre: "Survival", id: 76 },
  { genre: "Team Sports", id: 77 },
  { genre: "Time Travel", id: 78 },
  { genre: "Video Game", id: 79 },
  { genre: "Visual Arts", id: 80 },
];
